// HTML templates for each page.
const viz=k=>({chaos:`<svg viewBox="0 0 300 90" aria-label="Illustrative: chaotic nodes become a clear path"><g class="cz" stroke="#E8743B" fill="#FFF1E6" stroke-opacity=".9"><path d="M20 20L90 70L140 15L200 60L280 25M90 70L200 60M20 20L140 15" fill="none"/><circle cx="20" cy="20" r="5"/><circle cx="90" cy="70" r="5"/><circle cx="140" cy="15" r="5"/><circle cx="200" cy="60" r="5"/><circle cx="280" cy="25" r="5"/></g></svg>`,tele:`<svg viewBox="0 0 300 90" aria-label="Illustrative telemetry trace"><path d="M0 60 Q30 10 60 50T120 40T180 55T240 20T300 35" fill="none" stroke="#E8743B" stroke-width="1.5"/><path d="M0 80H300" stroke="#14234A" stroke-opacity=".15"/></svg>`,agent:`<div class="console">AGENT STATUS<br>NAVIGATING...<br>OBSERVING...<br>INTERACTING...<br>ANALYZING...</div>`})[k];
const card=(p,i)=>{const th=`<div class="thumb ${p.image||p.video?'':'g'+(i%3)}">${p.video?`<video src="${p.video.src}" autoplay muted loop playsinline preload="metadata" aria-label="${p.t}"></video>`:p.image?`<img src="${p.image}" alt="${p.t}">`:''}${p.soon?'<div class="soon"><b>Coming soon</b><span>Case study in progress</span></div>':''}</div><h3>${p.t}</h3><div class="co">${p.co}</div><p>${p.tags.join(' | ')}</p>${p.line?`<div class="ln">${p.line}</div>`:''}`;return p.soon?`<div class="pcard locked" data-c="${p.cat.join(' ')}" aria-label="${p.t} – coming soon, case study in progress">${th}</div>`:`<a class="pcard" href="#/projects/${p.slug}" data-c="${p.cat.join(' ')}">${th}</a>`};
const TABS=[["all","Selected"],["product","Product"],["ux","UX"],["research","Research"],["technology","Technology"],["ai","AI"]];
const projectsPage=()=>`<p class="intro">I'm Lilly, a product and technologist<br>who designs for people stuck in the middle<br>of a complicated tool.</p>
<div class="tabs" role="group" aria-label="Filter projects">${TABS.map((f,i)=>`<button data-f="${f[0]}" aria-pressed="${i==0}">${f[1]}</button>`).join('')}</div>
<div class="pgrid">${P.map(card).join('')}</div>${foot}`;
const foot=`<footer class="ft"><div><b>Lilly</b></div><div class="fl" role="navigation" aria-label="Footer"><a href="#/">Projects</a><a href="#/playground">Playground</a><a href="#/about">About</a></div></footer>`;
const pn=p=>{const i=P.indexOf(p),a=P[(i+P.length-1)%P.length],b=P[(i+1)%P.length];return`<div class="pn"><a class="btn" href="#/projects/${a.slug}">← ${a.co}</a><a class="btn" href="#/projects">All projects</a><a class="btn" href="#/projects/${b.slug}">${b.co} →</a></div>`};
const head=(l,t,s)=>`<h1>${t}</h1><p class="l">${s}</p>`;
const R={
"":()=>projectsPage(),

about:()=>`<div class="page">${head("","I like figuring out how things work — and how they could work better.","I'm Lilly, a product and technologist. I research complex problems and design for people who are stuck in the middle of a complicated tool.")}
<p class="l">My experience spans enterprise SaaS, scientific research software, UX research, product design, data visualization, front-end engineering, and AI-powered UX evaluation. Across each environment, I've worked on the same challenge: understanding complex systems and turning that understanding into clearer, more useful experiences.</p>
<section class="two"><div><h2>Skills, mapped</h2><p class="l">Select a node to see what sits behind it.</p><div class="panel" id="sk" aria-live="polite"><h3>Product</h3><p>${SK.Product}</p></div></div>
<svg id="const" viewBox="0 0 400 400" role="group" aria-label="Skill constellation">${Object.keys(SK).map((k,i)=>{if(i==0)return'';const a=(i-1)*72*Math.PI/180-1.57,x=200+140*Math.cos(a),y=200+140*Math.sin(a);return`<line x1="200" y1="200" x2="${x}" y2="${y}" stroke="#4C9BFF" stroke-opacity=".3"/><g class="cn" tabindex="0" role="button" data-k="${k}" transform="translate(${x} ${y})"><circle r="${k.length>8?44:k.length>6?34:28}"/><text y="4">${k.replace(' ',' ')}</text></g>`}).join('')}<g class="cn on" tabindex="0" role="button" data-k="Product" transform="translate(200 200)"><circle r="38"/><text y="4">Product</text></g></svg></section>
<section><h2>Experience</h2><div class="tl">${[["June – Sept 2026","Siemens","Product (PLM)"],["April – Dec 2026","NVIDIA","UX Researcher"],["June 2023 – June 2025","California NanoSystems Institute","UI Engineer"]].map(t=>`<div><span class="mono">${t[0]}</span><h3>${t[1]}</h3><p style="color:var(--tx2)">${t[2]}</p></div>`).join('')}</div></section></div>${foot}`,
projects:()=>projectsPage(),

playground:()=>`<div class="page">${head("","Not everything needs to become a project.","So here is a small game. Something is climbing the edge of this page.")}${gameHTML()}</div>${foot}`,
404:()=>`<div class="page"><h1>Page not found</h1><p class="l">That page doesn't exist.</p><div class="row"><a class="btn p" href="#/">Back to projects</a></div></div>${foot}`
};
const mi=(x,slotText)=>{if(!x)return`<div class="mslot"><span>${slotText}</span></div>`;return`<figure class="mi">${x.type==='video'?`<video src="${x.src}" controls autoplay muted loop playsinline preload="metadata"></video>`:x.type==='embed'?`<div class="emb"><iframe src="${x.src}" allowfullscreen loading="lazy" title="${x.caption||'Prototype'}"></iframe></div>`:`<img src="${x.src}" alt="${x.caption||'Prototype'}" loading="lazy">`}${x.caption?`<figcaption>${x.caption}</figcaption>`:''}</figure>`};
const media=p=>{const m=(typeof MEDIA!=='undefined'&&Array.isArray(MEDIA[p.slug])&&MEDIA[p.slug])||[];
return`<div class="sec"><div><h3>Prototypes</h3></div><div><div class="mgrid">${m.length?m.map(x=>mi(x)).join(''):mi(null,'Add prototype image or video')+mi(null,'Add prototype image or video')}</div>${m.length?'':'<p class="hint">Add your files in data/media.js (see comments there).</p>'}</div></div>`};
const visuals=(p,c)=>{const M=(typeof MEDIA!=='undefined'&&MEDIA[p.slug])||{};
const note=c.noMedia?`<div class="sec"><div><h3>Screens</h3><span class="mono">Note</span></div><div><div class="nomedia"><b>No screenshots</b><span>The original and redesigned screens belong to Siemens and cannot be shared publicly.</span></div></div></div>`:'';
return note+c.V.map(v=>{const g=M[v[0]]||{},f=g.flow||[];
return`<div class="sec vis"><div><h3>${v[1]}</h3><span class="mono">${c.noMedia?'Flow':'Visuals'}</span></div><div>${v[2].startsWith('<')?v[2]:'<p>'+v[2]+'</p>'}${c.noMedia?'':`<div class="cmp"><div><span class="tag">Original</span>${mi(g.before,'Add screenshot of the original')}</div><div><span class="tag n">Design suggestion</span>${mi(g.after,'Add screenshot of your design suggestion')}</div></div>${f.length?`<div class="mgrid" style="margin-top:24px">${f.map(x=>mi(x)).join('')}</div>`:''}`}</div></div>`}).join('')};
const soonPage=p=>`<div class="page"><a class="crumb mono" href="#/projects">← All projects</a><br><div class="mono">${p.co}</div><h1 style="margin-top:12px">${p.t}</h1><p class="l">Coming soon. This case study is in progress.</p>${pn(p)}</div>${foot}`;
const detailG=p=>{const S=[["Mission brief","What was the problem?"],["Context","What system or product was involved?"],["Investigation","How the problem was understood."],["Signals","What evidence emerged."],["Response","What was designed or built."],["Validation","How the solution was evaluated."],["Outcome","What changed."]];
return`<div class="page"><a class="crumb mono" href="#/projects">← All projects</a><br><div class="mono">${p.co} · ${p.slug=='nvidia-ucsc'?'In progress':'Complete'}</div><h1 style="margin-top:12px">${p.t}</h1><p class="l">${p.d}</p>
<div class="det">${[["Role",p.role],["Company",p.co],["Timeline",p.when],["Domain",p.dom],["Methods",p.meth]].map(m=>`<div><span class="mono">${m[0]}</span><b>${m[1]}</b></div>`).join('')}</div>
${S.map((s,i)=>`<div class="sec"><div><h3>${s[0]}</h3></div><div><p>${s[1]}</p><div class="ph">TO ADD: your real write-up, screenshots, and findings. Nothing here is a result.</div></div></div>`).join('')}
${pn(p)}</div>${foot}`};
const detail=p=>{if(p.soon)return soonPage(p);const c=CS[p.slug];if(!c)return detailG(p);
return`<div class="page"><a class="crumb mono" href="#/projects">← All projects</a><br><div class="mono">${c.status}</div><h1 style="margin-top:12px">${p.t}</h1><p class="l">${p.d}</p>
<div class="det">${[["Role",p.role],["Company",p.co],["Timeline",p.when],["Domain",p.dom],["Methods",p.meth]].map(m=>`<div><span class="mono">${m[0]}</span><b>${m[1]}</b></div>`).join('')}</div>
${c.S.map(x=>`<div class="sec"><div><h3>${x[0]}</h3></div><div>${x[1].startsWith('<')?x[1]:'<p>'+x[1]+'</p>'}</div></div>`+(c.V&&x[0]==c.after?visuals(p,c):'')+(c.M&&c.M[x[0]]?`<div class="sec"><div><h3>${c.M[x[0]][0]}</h3><span class="mono">Media</span></div><div><div class="mgrid even">${((MEDIA[p.slug]||{})[c.M[x[0]][1]]||[]).map(m=>mi(m)).join('')}</div></div></div>`:'')).join('')}
${c.V||c.M?'':c.soon?`<div class="sec"><div><h3>Prototype</h3></div><div><div class="soonbox"><b>Coming soon</b><span>${c.soon}</span></div></div></div>`:media(p)}
${pn(p)}</div>${foot}`};
